// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Przetrwaj.Infrastucture.Context;

#nullable disable

namespace Przetrwaj.Infrastucture.Migrations
{
	[DbContext(typeof(ApplicationDbContext))]
	[Migration("20260227110600_UserJwtRefresh")]
	partial class UserJwtRefresh
	{
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasDefaultSchema("przetrwaj")
				.HasAnnotation("ProductVersion", "9.0.11")
				.HasAnnotation("Relational:MaxIdentifierLength", 63);

			NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
				{
					b.Property<string>("Id")
						.HasColumnType("text");

					b.Property<string>("ConcurrencyStamp")
						.IsConcurrencyToken()
						.HasColumnType("text");

					b.Property<string>("Name")
						.HasMaxLength(256)
						.HasColumnType("character varying(256)");

					b.Property<string>("NormalizedName")
						.HasMaxLength(256)
						.HasColumnType("character varying(256)");

					b.HasKey("Id");

					b.HasIndex("NormalizedName")
						.IsUnique()
						.HasDatabaseName("RoleNameIndex");

					b.ToTable("AspNetRoles", "przetrwaj");

					b.HasData(
						new
						{
							Id = "c395bc61-a75a-44ea-a8b6-d136bb4e032e",
							Name = "User",
							NormalizedName = "USER"
						},
						new
						{
							Id = "aabf5428-e94c-418a-939a-8004bd1fe63c",
							Name = "Moderator",
							NormalizedName = "MODERATOR"
						},
						new
						{
							Id = "8411b424-3e32-4ea3-8dbc-b5d786b62e40",
							Name = "Admin",
							NormalizedName = "ADMIN"
						});
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

					b.Property<string>("ClaimType")
						.HasColumnType("text");

					b.Property<string>("ClaimValue")
						.HasColumnType("text");

					b.Property<string>("RoleId")
						.IsRequired()
						.HasColumnType("text");

					b.HasKey("Id");

					b.HasIndex("RoleId");

					b.ToTable("AspNetRoleClaims", "przetrwaj");
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

					b.Property<string>("ClaimType")
						.HasColumnType("text");

					b.Property<string>("ClaimValue")
						.HasColumnType("text");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("text");

					b.HasKey("Id");

					b.HasIndex("UserId");

					b.ToTable("AspNetUserClaims", "przetrwaj");
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
				{
					b.Property<string>("LoginProvider")
						.HasColumnType("text");

					b.Property<string>("ProviderKey")
						.HasColumnType("text");

					b.Property<string>("ProviderDisplayName")
						.HasColumnType("text");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("text");

					b.HasKey("LoginProvider", "ProviderKey");

					b.HasIndex("UserId");

					b.ToTable("AspNetUserLogins", "przetrwaj");
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
				{
					b.Property<string>("UserId")
						.HasColumnType("text");

					b.Property<string>("RoleId")
						.HasColumnType("text");

					b.HasKey("UserId", "RoleId");

					b.HasIndex("RoleId");

					b.ToTable("AspNetUserRoles", "przetrwaj");
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
				{
					b.Property<string>("UserId")
						.HasColumnType("text");

					b.Property<string>("LoginProvider")
						.HasColumnType("text");

					b.Property<string>("Name")
						.HasColumnType("text");

					b.Property<string>("Value")
						.HasColumnType("text");

					b.HasKey("UserId", "LoginProvider", "Name");

					b.ToTable("AspNetUserTokens", "przetrwaj");
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.AppUser", b =>
				{
					b.Property<string>("Id")
						.HasColumnType("text");

					b.Property<int>("AccessFailedCount")
						.HasColumnType("integer");

					b.Property<DateTimeOffset?>("BanDate")
						.HasColumnType("timestamp with time zone");

					b.Property<string>("BanReason")
						.HasColumnType("text");

					b.Property<string>("BannedById")
						.HasColumnType("text");

					b.Property<string>("ConcurrencyStamp")
						.IsConcurrencyToken()
						.HasColumnType("text");

					b.Property<string>("Email")
						.HasMaxLength(256)
						.HasColumnType("character varying(256)");

					b.Property<bool>("EmailConfirmed")
						.HasColumnType("boolean");

					b.Property<int?>("GminaId")
						.HasColumnType("integer");

					b.Property<int>("Impediments")
						.HasColumnType("integer");

					b.Property<bool>("LockoutEnabled")
						.HasColumnType("boolean");

					b.Property<DateTimeOffset?>("LockoutEnd")
						.HasColumnType("timestamp with time zone");

					b.Property<bool>("ModeratorRolePending")
						.HasColumnType("boolean");

					b.Property<DateTimeOffset?>("ModeratorSince")
						.HasColumnType("timestamp with time zone");

					b.Property<string>("Name")
						.HasColumnType("text");

					b.Property<string>("NormalizedEmail")
						.HasMaxLength(256)
						.HasColumnType("character varying(256)");

					b.Property<string>("NormalizedUserName")
						.HasMaxLength(256)
						.HasColumnType("character varying(256)");

					b.Property<string>("PasswordHash")
						.HasColumnType("text");

					b.Property<string>("PhoneNumber")
						.HasColumnType("text");

					b.Property<bool>("PhoneNumberConfirmed")
						.HasColumnType("boolean");

					b.Property<short?>("PowiatId")
						.HasColumnType("smallint");

					b.Property<DateTimeOffset>("RegistrationDate")
						.HasColumnType("timestamp with time zone");

					b.Property<string>("SecurityStamp")
						.HasColumnType("text");

					b.Property<string>("Surname")
						.HasColumnType("text");

					b.Property<bool>("TwoFactorEnabled")
						.HasColumnType("boolean");

					b.Property<string>("UserName")
						.HasMaxLength(256)
						.HasColumnType("character varying(256)");

					b.HasKey("Id");

					b.HasIndex("GminaId");

					b.HasIndex("NormalizedEmail")
						.HasDatabaseName("EmailIndex");

					b.HasIndex("NormalizedUserName")
						.IsUnique()
						.HasDatabaseName("UserNameIndex");

					b.HasIndex("PowiatId");

					b.ToTable("AspNetUsers", "przetrwaj");
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.Attachment", b =>
				{
					b.Property<string>("IdAttachment")
						.HasMaxLength(64)
						.HasColumnType("character varying(64)");

					b.Property<string>("AlternateDescription")
						.HasColumnType("text");

					b.Property<string>("IdPost")
						.IsRequired()
						.HasMaxLength(36)
						.HasColumnType("character varying(36)");

					b.Property<int>("OrderInList")
						.HasColumnType("integer");

					b.HasKey("IdAttachment");

					b.HasIndex("IdPost");

					b.ToTable("Attachments", "przetrwaj");
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.Category", b =>
				{
					b.Property<int>("IdCategory")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategory"));

					b.Property<string>("CategoryIcon")
						.HasColumnType("text");

					b.Property<int>("Impediments")
						.HasColumnType("integer");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("text");

					b.Property<int>("Type")
						.HasColumnType("integer");

					b.HasKey("IdCategory");

					b.ToTable("Categories", "przetrwaj");

					b.HasDiscriminator<int>("Type");

					b.UseTphMappingStrategy();
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.Impediment", b =>
				{
					b.Property<short>("Id")
						.HasColumnType("smallint");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("text");

					b.HasKey("Id");

					b.ToTable("Impediments", "przetrwaj");
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.Post", b =>
				{
					b.Property<string>("IdPost")
						.HasMaxLength(36)
						.HasColumnType("character varying(36)");

					b.Property<bool>("Active")
						.HasColumnType("boolean");

					b.Property<int>("CategoryType")
						.HasColumnType("integer");

					b.Property<string>("CustomCategory")
						.IsRequired()
						.HasColumnType("text");

					b.Property<DateTimeOffset>("DateCreated")
						.HasColumnType("timestamp with time zone");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("text");

					b.Property<string>("IdAutor")
						.IsRequired()
						.HasMaxLength(36)
						.HasColumnType("character varying(36)");

					b.Property<int>("IdCategory")
						.HasColumnType("integer");

					b.Property<int?>("IdGmiOnly")
						.HasColumnType("integer");

					b.Property<short?>("IdPowOnly")
						.HasColumnType("smallint");

					b.Property<short?>("IdWojOnly")
						.HasColumnType("smallint");

					b.Property<double?>("Lat")
						.HasColumnType("double precision");

					b.Property<double?>("Long")
						.HasColumnType("double precision");

					b.Property<string>("Title")
						.IsRequired()
						.HasColumnType("text");

					b.HasKey("IdPost");

					b.HasIndex("IdAutor");

					b.HasIndex("IdCategory");

					b.HasIndex("IdGmiOnly");

					b.HasIndex("IdPowOnly");

					b.HasIndex("IdWojOnly");

					b.HasIndex("CategoryType", "Active")
						.HasDatabaseName("IX_Post_Category_Active");

					b.ToTable("Posts", "przetrwaj");
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.RegionGmi", b =>
				{
					b.Property<int>("Id")
						.HasColumnType("integer");

					b.Property<double>("Lat")
						.HasColumnType("double precision");

					b.Property<double>("Long")
						.HasColumnType("double precision");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("text");

					b.Property<short>("PowId")
						.HasColumnType("smallint");

					b.HasKey("Id");

					b.HasIndex("PowId");

					b.ToTable("RegionGmi", "przetrwaj");
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.RegionPow", b =>
				{
					b.Property<short>("Id")
						.HasColumnType("smallint");

					b.Property<double>("Lat")
						.HasColumnType("double precision");

					b.Property<double>("Long")
						.HasColumnType("double precision");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("text");

					b.Property<short>("WojId")
						.HasColumnType("smallint");

					b.HasKey("Id");

					b.HasIndex("WojId");

					b.ToTable("RegionPow", "przetrwaj");
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.RegionWoj", b =>
				{
					b.Property<short>("Id")
						.HasColumnType("smallint");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("text");

					b.HasKey("Id");

					b.ToTable("RegionWoj", "przetrwaj");

					b.HasData(
						new
						{
							Id = (short)0,
							Name = "Polska"
						});
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.UserComment", b =>
				{
					b.Property<string>("IdComment")
						.HasMaxLength(36)
						.HasColumnType("character varying(36)");

					b.Property<string>("Comment")
						.IsRequired()
						.HasColumnType("text");

					b.Property<DateTimeOffset>("DateCreated")
						.HasColumnType("timestamp with time zone");

					b.Property<string>("IdAutor")
						.IsRequired()
						.HasMaxLength(36)
						.HasColumnType("character varying(36)");

					b.Property<string>("IdPost")
						.IsRequired()
						.HasMaxLength(36)
						.HasColumnType("character varying(36)");

					b.HasKey("IdComment");

					b.HasIndex("IdAutor");

					b.HasIndex("IdPost");

					b.ToTable("Comments", "przetrwaj");
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.UserJwtRefresh", b =>
				{
					b.Property<string>("UserId")
						.HasColumnType("text")
						.HasAnnotation("Relational:JsonPropertyName", "UID");

					b.Property<string>("Jwi")
						.HasColumnType("text");

					b.Property<string>("RefreshToken")
						.IsRequired()
						.HasColumnType("text")
						.HasAnnotation("Relational:JsonPropertyName", "RT");

					b.Property<short>("UsesLeft")
						.HasColumnType("smallint")
						.HasAnnotation("Relational:JsonPropertyName", "UL");

					b.Property<DateTimeOffset>("ValidTill")
						.HasColumnType("timestamp with time zone")
						.HasAnnotation("Relational:JsonPropertyName", "VT");

					b.HasKey("UserId", "Jwi");

					b.ToTable("UserJwtRefresh", "auth");
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.Vote", b =>
				{
					b.Property<string>("IdPost")
						.HasMaxLength(36)
						.HasColumnType("character varying(36)");

					b.Property<string>("IdUser")
						.HasMaxLength(36)
						.HasColumnType("character varying(36)");

					b.Property<bool>("IsUpvote")
						.HasColumnType("boolean");

					b.HasKey("IdPost", "IdUser");

					b.HasIndex("IdUser");

					b.ToTable("Votes", "przetrwaj");
				});

			modelBuilder.Entity("Przetrwaj.Domain.Models.Dtos.Posts.PostMinimalCategoryRegion", b =>
				{
					b.Property<bool>("Active")
						.HasColumnType("boolean");

					b.Property<int>("IdCategory")
						.HasColumnType("integer");

					b.Property<string>("IdPost")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("IdPost");

					b.Property<double>("Lat")
						.HasColumnType("double precision");

					b.Property<double>("Long")
						.HasColumnType("double precision");

					b.Property<string>("Title")
						.IsRequired()
						.HasColumnType("text");

					b.ToTable((string)null);

					b.ToView("View_PostMinimal", "przetrwaj");
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.CategoryDanger", b =>
				{
					b.HasBaseType("Przetrwaj.Domain.Entities.Category");

					b.HasDiscriminator().HasValue(0);
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.CategoryResource", b =>
				{
					b.HasBaseType("Przetrwaj.Domain.Entities.Category");

					b.HasDiscriminator().HasValue(1);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
				{
					b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
						.WithMany()
						.HasForeignKey("RoleId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
				{
					b.HasOne("Przetrwaj.Domain.Entities.AppUser", null)
						.WithMany()
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
				{
					b.HasOne("Przetrwaj.Domain.Entities.AppUser", null)
						.WithMany()
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
				{
					b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
						.WithMany()
						.HasForeignKey("RoleId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("Przetrwaj.Domain.Entities.AppUser", null)
						.WithMany()
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
				{
					b.HasOne("Przetrwaj.Domain.Entities.AppUser", null)
						.WithMany()
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.AppUser", b =>
				{
					b.HasOne("Przetrwaj.Domain.Entities.RegionGmi", "RegionGmiNavigation")
						.WithMany()
						.HasForeignKey("GminaId")
						.OnDelete(DeleteBehavior.SetNull);

					b.HasOne("Przetrwaj.Domain.Entities.RegionPow", "RegionPowNavigation")
						.WithMany("Users")
						.HasForeignKey("PowiatId")
						.OnDelete(DeleteBehavior.SetNull);

					b.Navigation("RegionGmiNavigation");

					b.Navigation("RegionPowNavigation");
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.Attachment", b =>
				{
					b.HasOne("Przetrwaj.Domain.Entities.Post", "IdPostNavigation")
						.WithMany("Attachments")
						.HasForeignKey("IdPost")
						.OnDelete(DeleteBehavior.SetNull)
						.IsRequired();

					b.Navigation("IdPostNavigation");
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.Post", b =>
				{
					b.HasOne("Przetrwaj.Domain.Entities.AppUser", "IdAutorNavigation")
						.WithMany("Posts")
						.HasForeignKey("IdAutor")
						.OnDelete(DeleteBehavior.Restrict)
						.IsRequired();

					b.HasOne("Przetrwaj.Domain.Entities.Category", "IdCategoryNavigation")
						.WithMany("Posts")
						.HasForeignKey("IdCategory")
						.OnDelete(DeleteBehavior.Restrict)
						.IsRequired();

					b.HasOne("Przetrwaj.Domain.Entities.RegionGmi", "RegionGmiNavigation")
						.WithMany("Posts")
						.HasForeignKey("IdGmiOnly")
						.OnDelete(DeleteBehavior.Restrict);

					b.HasOne("Przetrwaj.Domain.Entities.RegionPow", "RegionPowNavigation")
						.WithMany("Posts")
						.HasForeignKey("IdPowOnly")
						.OnDelete(DeleteBehavior.Restrict);

					b.HasOne("Przetrwaj.Domain.Entities.RegionWoj", "RegionWojNavigation")
						.WithMany("Posts")
						.HasForeignKey("IdWojOnly")
						.OnDelete(DeleteBehavior.Restrict);

					b.Navigation("IdAutorNavigation");

					b.Navigation("IdCategoryNavigation");

					b.Navigation("RegionGmiNavigation");

					b.Navigation("RegionPowNavigation");

					b.Navigation("RegionWojNavigation");
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.RegionGmi", b =>
				{
					b.HasOne("Przetrwaj.Domain.Entities.RegionPow", "Pow")
						.WithMany("Gminy")
						.HasForeignKey("PowId")
						.OnDelete(DeleteBehavior.Restrict)
						.IsRequired();

					b.Navigation("Pow");
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.RegionPow", b =>
				{
					b.HasOne("Przetrwaj.Domain.Entities.RegionWoj", "Woj")
						.WithMany("Powiaty")
						.HasForeignKey("WojId")
						.OnDelete(DeleteBehavior.Restrict)
						.IsRequired();

					b.Navigation("Woj");
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.UserComment", b =>
				{
					b.HasOne("Przetrwaj.Domain.Entities.AppUser", "IdAutorNavigation")
						.WithMany("Comments")
						.HasForeignKey("IdAutor")
						.OnDelete(DeleteBehavior.Restrict)
						.IsRequired();

					b.HasOne("Przetrwaj.Domain.Entities.Post", "IdPostNavigation")
						.WithMany("Comments")
						.HasForeignKey("IdPost")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("IdAutorNavigation");

					b.Navigation("IdPostNavigation");
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.UserJwtRefresh", b =>
				{
					b.HasOne("Przetrwaj.Domain.Entities.AppUser", null)
						.WithMany()
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.Vote", b =>
				{
					b.HasOne("Przetrwaj.Domain.Entities.Post", "IdPostNavigation")
						.WithMany("Votes")
						.HasForeignKey("IdPost")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("Przetrwaj.Domain.Entities.AppUser", "IdUserNavigation")
						.WithMany()
						.HasForeignKey("IdUser")
						.OnDelete(DeleteBehavior.Restrict)
						.IsRequired();

					b.Navigation("IdPostNavigation");

					b.Navigation("IdUserNavigation");
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.AppUser", b =>
				{
					b.Navigation("Comments");

					b.Navigation("Posts");
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.Category", b =>
				{
					b.Navigation("Posts");
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.Post", b =>
				{
					b.Navigation("Attachments");

					b.Navigation("Comments");

					b.Navigation("Votes");
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.RegionGmi", b =>
				{
					b.Navigation("Posts");
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.RegionPow", b =>
				{
					b.Navigation("Gminy");

					b.Navigation("Posts");

					b.Navigation("Users");
				});

			modelBuilder.Entity("Przetrwaj.Domain.Entities.RegionWoj", b =>
				{
					b.Navigation("Posts");

					b.Navigation("Powiaty");
				});
#pragma warning restore 612, 618
		}
	}
}
