// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Przetrwaj.Infrastucture.Context;

#nullable disable

namespace Przetrwaj.Infrastucture.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("przetrwaj")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", "przetrwaj");

                    b.HasData(
                        new
                        {
                            Id = "c395bc61-a75a-44ea-a8b6-d136bb4e032e",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "aabf5428-e94c-418a-939a-8004bd1fe63c",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = "8411b424-3e32-4ea3-8dbc-b5d786b62e40",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "przetrwaj");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "przetrwaj");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "przetrwaj");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "przetrwaj");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "przetrwaj");
                });

            modelBuilder.Entity("Przetrwaj.Domain.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("BanDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BanReason")
                        .HasColumnType("text");

                    b.Property<string>("BannedById")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("GminaId")
                        .HasColumnType("integer");

                    b.Property<int>("Impediments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ModeratorRolePending")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModeratorSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("GminaId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", "przetrwaj");
                });

            modelBuilder.Entity("Przetrwaj.Domain.Entities.Attachment", b =>
                {
                    b.Property<string>("IdAttachment")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AlternateDescription")
                        .HasColumnType("text");

                    b.Property<string>("IdPost")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<int>("OrderInList")
                        .HasColumnType("integer");

                    b.HasKey("IdAttachment");

                    b.HasIndex("IdPost");

                    b.ToTable("Attachments", "przetrwaj");
                });

            modelBuilder.Entity("Przetrwaj.Domain.Entities.Category", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategory"));

                    b.Property<string>("CategoryIcon")
                        .HasColumnType("text");

                    b.Property<int>("Impediments")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("IdCategory");

                    b.ToTable("Categories", "przetrwaj");

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Przetrwaj.Domain.Entities.Impediment", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Impediments", "przetrwaj");
                });

            modelBuilder.Entity("Przetrwaj.Domain.Entities.Post", b =>
                {
                    b.Property<string>("IdPost")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("CategoryType")
                        .HasColumnType("integer");

                    b.Property<string>("CustomCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdAutor")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<int>("IdCategory")
                        .HasColumnType("integer");

                    b.Property<int>("IdRegion")
                        .HasColumnType("integer");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Long")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdPost");

                    b.HasIndex("IdAutor");

                    b.HasIndex("IdCategory");

                    b.HasIndex("IdRegion");

                    b.HasIndex("CategoryType", "Active")
                        .HasDatabaseName("IX_Post_Category_Active");

                    b.ToTable("Posts", "przetrwaj");
                });

            modelBuilder.Entity("Przetrwaj.Domain.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("RegionType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Regions", "przetrwaj");

                    b.HasDiscriminator<int>("RegionType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Przetrwaj.Domain.Entities.UserComment", b =>
                {
                    b.Property<string>("IdComment")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdAutor")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("IdPost")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.HasKey("IdComment");

                    b.HasIndex("IdAutor");

                    b.HasIndex("IdPost");

                    b.ToTable("Comments", "przetrwaj");
                });

            modelBuilder.Entity("Przetrwaj.Domain.Entities.UserJwtRefresh", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Jwi")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("UsesLeft")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("ValidTill")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "Jwi");

                    b.ToTable("UserJwtRefresh", "auth");
                });

            modelBuilder.Entity("Przetrwaj.Domain.Entities.Vote", b =>
                {
                    b.Property<string>("IdPost")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("IdUser")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<bool>("IsUpvote")
                        .HasColumnType("boolean");

                    b.HasKey("IdPost", "IdUser");

                    b.HasIndex("IdUser");

                    b.ToTable("Votes", "przetrwaj");
                });

            modelBuilder.Entity("Przetrwaj.Domain.Models.Dtos.Posts.PostMinimalCategoryRegion", b =>
                {
                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("IdCategory")
                        .HasColumnType("integer");

                    b.Property<string>("IdPost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Long")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable((string)null);

                    b.ToView("View_PostMinimal", "przetrwaj");
                });

            modelBuilder.Entity("Przetrwaj.Domain.Entities.CategoryDanger", b =>
                {
                    b.HasBaseType("Przetrwaj.Domain.Entities.Category");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Przetrwaj.Domain.Entities.CategoryResource", b =>
                {
                    b.HasBaseType("Przetrwaj.Domain.Entities.Category");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Przetrwaj.Domain.Entities.RegionGmi", b =>
                {
                    b.HasBaseType("Przetrwaj.Domain.Entities.Region");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Przetrwaj.Domain.Entities.RegionPow", b =>
                {
                    b.HasBaseType("Przetrwaj.Domain.Entities.Region");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Przetrwaj.Domain.Entities.RegionWoj", b =>
                {
                    b.HasBaseType("Przetrwaj.Domain.Entities.Region");

                    b.HasDiscriminator().HasValue(1);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "Polska"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Przetrwaj.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Przetrwaj.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Przetrwaj.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Przetrwaj.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Przetrwaj.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("Przetrwaj.Domain.Entities.Region", "RegionNavigation")
                        .WithMany()
                        .HasForeignKey("GminaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RegionNavigation");
                });

            modelBuilder.Entity("Przetrwaj.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("Przetrwaj.Domain.Entities.Post", "IdPostNavigation")
                        .WithMany("Attachments")
                        .HasForeignKey("IdPost")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("IdPostNavigation");
                });

            modelBuilder.Entity("Przetrwaj.Domain.Entities.Post", b =>
                {
                    b.HasOne("Przetrwaj.Domain.Entities.AppUser", "IdAutorNavigation")
                        .WithMany("Posts")
                        .HasForeignKey("IdAutor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Przetrwaj.Domain.Entities.Category", "IdCategoryNavigation")
                        .WithMany("Posts")
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Przetrwaj.Domain.Entities.Region", "RegionNavigation")
                        .WithMany("Posts")
                        .HasForeignKey("IdRegion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdAutorNavigation");

                    b.Navigation("IdCategoryNavigation");

                    b.Navigation("RegionNavigation");
                });

            modelBuilder.Entity("Przetrwaj.Domain.Entities.Region", b =>
                {
                    b.HasOne("Przetrwaj.Domain.Entities.Region", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Przetrwaj.Domain.Entities.UserComment", b =>
                {
                    b.HasOne("Przetrwaj.Domain.Entities.AppUser", "IdAutorNavigation")
                        .WithMany("Comments")
                        .HasForeignKey("IdAutor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Przetrwaj.Domain.Entities.Post", "IdPostNavigation")
                        .WithMany("Comments")
                        .HasForeignKey("IdPost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdAutorNavigation");

                    b.Navigation("IdPostNavigation");
                });

            modelBuilder.Entity("Przetrwaj.Domain.Entities.UserJwtRefresh", b =>
                {
                    b.HasOne("Przetrwaj.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Przetrwaj.Domain.Entities.Vote", b =>
                {
                    b.HasOne("Przetrwaj.Domain.Entities.Post", "IdPostNavigation")
                        .WithMany("Votes")
                        .HasForeignKey("IdPost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Przetrwaj.Domain.Entities.AppUser", "IdUserNavigation")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdPostNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Przetrwaj.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Przetrwaj.Domain.Entities.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Przetrwaj.Domain.Entities.Post", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Comments");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Przetrwaj.Domain.Entities.Region", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
