<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Queries\AccountQuaries\**" />
    <EmbeddedResource Remove="Queries\AccountQuaries\**" />
    <None Remove="Queries\AccountQuaries\**" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="Azure.Communication.Email" Version="1.1.0" />
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="9.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.12" />
    <PackageReference Include="MailKit" Version="4.11.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.11" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Przetrwaj.Domain\Przetrwaj.Domain.csproj" />
  </ItemGroup>

</Project>
