using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Net.Http.Headers;

namespace PrzetrwajPL.Security;

public class JwtAuthorizationHandler : DelegatingHandler
{
	private readonly IHttpContextAccessor _httpContextAccessor;

	public JwtAuthorizationHandler(IHttpContextAccessor httpContextAccessor)
	{
		_httpContextAccessor = httpContextAccessor;
	}

	protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	{
		var context = _httpContextAccessor.HttpContext;

		// If you are forwarding the cookie generated by AccountController:
		//var cookie = context.Request.Headers[CookieAuthenticationDefaults.AuthenticationScheme].ToString();
		//if (!string.IsNullOrEmpty(cookie))
		//{
		//	request.Headers.Add(CookieAuthenticationDefaults.AuthenticationScheme, cookie);
		//}

		// If you are using JWT directly in the header:
		var token = await context.GetTokenAsync("access_token");
		if (!string.IsNullOrEmpty(token))
		{
			request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
		}

		return await base.SendAsync(request, cancellationToken);
	}
}